core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('', views.index, name='inicio'),
    path('download-report/', views.generate_report, name='download-report'),
    path('download-tag/', views.generate_tags, name='download-tag'),
]

customers/urls.py
from django.urls import path
from .views import CustomerCreateView, CustomerDeleteView, CustomerDetailView, CustomerListView, CustomerUpdateView, export_telegrama

app_name = 'customers'
urlpatterns = [
    path('', CustomerListView.as_view(), name='clientes'),
    path('cadastrar/', CustomerCreateView.as_view(), name='cadastrar'),
    path('<int:pk>', CustomerDetailView.as_view(), name='cliente'),
    path('excluir/<int:pk>', CustomerDeleteView.as_view(), name='excluir'),
    path('editar/<int:pk>', CustomerUpdateView.as_view(), name='editar'),
    path('download/', export_telegrama, name="download"),
]

maladireta/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('users.urls')),
    path('cargos/', include('positions.urls')),
    path('instituicoes/', include('institutions.urls')),
    path('autoridades/', include('authorities.urls')),
    path('liderancas/', include('leadership.urls')),
    path('partidos/', include('parties.urls')),
    path('candidatos/', include('candidates.urls')),
    path('clientes/', include('customers.urls')),
    path('funcionarios/', include('employees.urls')),
    path('pleitos/', include('solicitations.urls')),
]

customers/models.py
from django.db import models
from django.urls import reverse
import datetime

class CustomerManager(models.Manager):
    def search(self, query):
        if "Referencia:" in query:
            office = query.split(":")[1].replace(" ","")
            return self.get_queryset().filter(models.Q(reference__icontains=office))
        elif "Lideranca:" in query:
            office = query.split(":")[1].replace(" ","")
            return self.get_queryset().filter(models.Q(leadership__icontains=office))
        elif "Dia:" in query:
            day = query.split(":")[1]
            month = datetime.date.today().month
            return self.get_queryset().filter(models.Q(birth__day=day)).filter(models.Q(birth__month=month))
        elif "Mes:" in query:
            month = query.split(":")[1]
            return self.get_queryset().filter(models.Q(birth__month=month)).order_by('birth__month', 'birth__day')
        elif "Entre: " in query:
            first_day = query.split(":")[1].split(" e ")[0]
            last_day = query.split(":")[1].split(" e ")[1].split(" ")[0]
            month = query.split(" de ")[1]
            return self.get_queryset().filter(models.Q(birth__day__gte=first_day)).filter(models.Q(birth__day__lte=last_day)).filter(models.Q(birth__month=month)).order_by('birth__month', 'birth__day')
        return self.get_queryset().filter(models.Q(name__icontains=query) |
            models.Q(nickname__iexact=query) |
            models.Q(profession__icontains=query))

class Customer(models.Model):
    name = models.CharField(max_length=250)
    birth = models.DateField(blank=True, null=True)
    nickname = models.CharField(max_length=80, blank=True, null=True)
    reference = models.CharField(max_length=180, blank=True, null=True)
    city = models.CharField(max_length=80, blank=True, null=True)
    street = models.CharField(max_length=200, blank=True, null=True)
    number = models.CharField(max_length=25, blank=True, null=True)
    complement = models.CharField(max_length=30, blank=True, null=True)
    cep = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    neighborhood = models.CharField(max_length=60, blank=True, null=True)
    rg = models.CharField(max_length=25, blank=True, null=True)
    cpf = models.CharField(max_length=14, blank=True, null=True)
    phone_number = models.CharField(max_length=25, blank=True, null=True)
    cellphone = models.CharField(max_length=25, blank=True, null=True)
    phone_home = models.CharField(max_length=25, blank=True, null=True)
    leadership = models.CharField(max_length=25, blank=True, null=True)
    subscription = models.CharField(max_length=30, blank=True, null=True)
    zone = models.CharField(max_length=30, blank=True, null=True)
    section = models.CharField(max_length=30, blank=True, null=True)
    profession = models.CharField(max_length=80, blank=True, null=True)
    recurrence = models.CharField(max_length=60, blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    updated = models.DateField(auto_now=True)
    location_reference = models.TextField(blank=True, null=True)
    old_id = models.CharField(max_length=15, blank=True, null=True)

    objects = CustomerManager()

    def get_absolute_url(self):
        return reverse('customers:cliente', args=[str(self.id)])
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name"]

customers/forms.py
from django import forms
from .models import Customer

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"
        labels = {
            'name': 'Nome',
            'birth': 'Nascimento',
            'nickname': 'Pseudonimo',
            'reference': 'Referência',
            'city': 'Cidade',
            'street': 'Rua',
            'number': 'Número',
            'complement': 'Complemento',
            'cep': 'CEP',
            'state': 'Estado',
            'neighborhood': 'Bairro',
            'rg': 'RG',
            'cpf': 'CPF',
            'phone_number': 'Telefone',
            'cellphone': 'Celular',
            'phone_home': 'Residencial',
            'leadership': 'Liderança',
            'subscription': 'Inscrição',
            'zone': 'Zona',
            'section': 'Seção',
            'profession': 'Profissão',
            'recurrence': 'Retorno',
            'location_reference': 'Ref. Local',
            'note': 'Observação'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'birth': forms.DateInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'nickname': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'reference': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'city': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'street': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'number': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'complement': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'cep': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"00.000-000"}),
            'state': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'neighborhood': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'rg': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'cpf': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"000.000.000-00"}),
            'phone_number': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"(00)0000-0000"}),
            'phone_home': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"(00)0000-0000"}),
            'cellphone': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"(00)00000-0000"}),
            'leadership': forms.TextInput(attrs={'class':"form-control cc-name valid"}),
            'subscription': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'zone': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'section': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'email': forms.EmailInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'profession': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'recurrence': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'note': forms.Textarea(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'location_reference': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'})
        }
        error_messages = {
            'name': {
                'required': "Nome é um campo obrigatório"
            }
        }

customers/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse

from .models import Customer
from .forms import CustomerForm

def export_telegrama(request):
        query = request.session.get("query_filter")
        if query:
            content = [ "{}#Sr(a)#{}#{}#{}#{}#{}#{}#{}#Brasil#######\n".format(customer.name,
                        customer.name, customer.street,
                        customer.neighborhood, customer.number,
                        customer.city, customer.state,
                        customer.cep.replace('.','').replace('-',''))
                        for customer in Customer.objects.search(query)]
        else:
            content = [ "{}#Sr(a)#{}#{}#{}#{}#{}#{}#{}#Brasil#######\n".format(customer.name,
                        customer.name, customer.street,
                        customer.neighborhood, customer.number,
                        customer.city, customer.state,
                        customer.cep.replace('.','').replace('-',''))
                        for customer in Customer.objects.all() ]

        filename = "telegrama_clientes.txt"
        response = HttpResponse(content, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
        return response

class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    success_url = reverse_lazy('customers:clientes')
    form_class = CustomerForm

    def form_valid(self, form):
        super(CustomerCreateView, self).form_valid(form)
        messages.success(self.request, 'Cliente criado com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customer

class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('customers:clientes')
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Cliente excluído com sucesso!')
        return super(CustomerDeleteView, self).delete(request, *args, **kwargs)

class CustomerListView(LoginRequiredMixin, ListView):
    model = Customer
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not context.get('is_paginated', False):
            return context
        
        paginator = context.get('paginator')
        num_pages = paginator.num_pages
        current_page = context.get('page_obj')
        page_no = current_page.number
        

        if num_pages <= 11 or page_no <= 6:
            pages = [x for x in range(1, min(num_pages + 1, 12))]
        elif page_no > num_pages - 6:
            pages = [x for x in range(num_pages - 10, num_pages + 1)]
        else:
            pages = [x for x in range(page_no - 5, page_no + 6)]
        

        context.update({'pages': pages, 'previous_page': pages[0], 'next_page': pages[-1]})
        return context
        

    def get_queryset(self):
        filter_value = self.request.GET.get('filter')
        self.request.session['query_origin'] = 'Customer'
        if filter_value:
            context = Customer.objects.search(filter_value)
            self.request.session['query_filter'] = filter_value
        else:
            context = Customer.objects.all()
            self.request.session['query_filter'] = None
        return context

class CustomerUpdateView(LoginRequiredMixin, UpdateView):
    model = Customer
    success_url = reverse_lazy('customers:clientes')
    template_name = 'customers/customer_update_form.html'
    form_class = CustomerForm

    def form_valid(self, form):
        super(CustomerUpdateView, self).form_valid(form)
        messages.success(self.request, 'Cliente atualizado com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

templates/customers/customer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-6">
			<div class="card">
				<div class="card-header">Excluir Cliente</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
						{% csrf_token %}
                        <div class="form-group">
                            <p>Deseja excluir o cliente "{{ object }}"?</p>
                        </div>
                        <button type="submit" class="btn btn-danger btn-md">
                            <i class="fa fa-ban"></i> Excluir
                        </button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/customers/customer_form.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
{% include 'messages/error.html' %}
{% endif %}

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">Criar Cliente</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
						{% csrf_token %}
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.name.label_tag }}</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.nickname.label_tag }}</label>
                                    {{ form.nickname }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.birth.label_tag }}</label>
                                    {{ form.birth }}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.rg.label_tag }}</label>
                                    {{ form.rg }}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.cpf.label_tag }}</label>
                                    {{ form.cpf }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.email.label_tag }}</label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.profession.label_tag }}</label>
                                    {{ form.profession }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.phone_number.label_tag }}</label>
                                    {{ form.phone_number }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.phone_home.label_tag }}</label>
                                    {{ form.phone_home }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.cellphone.label_tag }}</label>
                                    {{ form.cellphone }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.reference.label_tag }}</label>
                                    {{ form.reference }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.leadership.label_tag }}</label>
                                    {{ form.leadership }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.subscription.label_tag }}</label>
                                    {{ form.subscription }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.zone.label_tag }}</label>
                                    {{ form.zone }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.section.label_tag }}</label>
                                    {{ form.section }}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.street.label_tag }}</label>
                                    {{ form.street }}
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.number.label_tag }}</label>
                                    {{ form.number }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.complement.label_tag }}</label>
                                    {{ form.complement }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.neighborhood.label_tag }}</label>
                                    {{ form.neighborhood }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.city.label_tag }}</label>
                                    {{ form.city }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.state.label_tag }}</label>
                                    {{ form.state }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.cep.label_tag }}</label>
                                    {{ form.cep }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.location_reference.label_tag }}</label>
                                    {{ form.location_reference }}
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.recurrence.label_tag }}</label>
                                    {{ form.recurrence }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.note.label_tag }}</label>
                                    {{ form.note }}
                                </div>
                            </div>
                        </div>
                        <div class="form-actions form-group">
                            <button type="submit" class="btn btn-primary btn-md">Salvar</button>
                        </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/customers/customer_list.html
{% extends 'base.html' %}

{% block content %}

{% load app_tags %}

{% if messages %}
{% include 'messages/message.html' %}
{% endif %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- DATA TABLE -->
            <h3 class="title-3 m-b-30">Clientes</h3>
            <div class="table-data__tool">
                <div class="table-data__tool-left">
                    <form method="get">
                        <div class="rs-select2--light rs-select2--lg">
                            <input type="text" title="Referencia: busca&#013;Lideranca: busca&#013;Dia: xx&#013;Mes: xx&#013;Entre: 01 e 15 de 06" id="filter" name="filter" class="form-control">
                        </div>
                        <button id="search" class="au-btn-filter">
                            <i class="zmdi zmdi-search"></i>Buscar</button>
                    </form>
                </div>
                <div class="table-data__tool-right">
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'customers:cadastrar' %}'">
                        <i class="zmdi zmdi-plus"></i>Criar</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'customers:download' %}'">
                        <i class="zmdi zmdi-email"></i>Correios</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'core:download-report' %}'">
                        <i class="zmdi zmdi-archive"></i>Relatório</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'core:download-tag' %}'">
                        <i class="zmdi zmdi-archive"></i>Etiquetas</button>
                </div>
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Pseudonimo</th>
                            <th>Referência</th>
                            <th>Liderança</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for customer in object_list %}
                            <tr>
                                <td>{{ customer.name }}</td>
                                <td>{{ customer.nickname }}</td>
                                <td>{{ customer.reference }}</td>
                                <td>{{ customer.leadership }}</td>
                                <td>
                                    <div class="table-data-feature">
                                        <a class="item" data-toggle="tooltip" data-placement="top" title="Detalhes" href="{% url 'customers:cliente' customer.pk %}">
                                            <i class="zmdi zmdi-file-text"></i>
                                        </a>
                                        <a class="item" data-toggle="tooltip" data-placement="top" title="Editar" href="{% url 'customers:editar' customer.pk %}">
                                            <i class="zmdi zmdi-edit"></i>
                                        </a>
                                        <a class="item" data-toggle="tooltip" data-placement="top" title="Excluir" href="{% url 'customers:excluir' customer.pk %}">
                                            <i class="zmdi zmdi-delete"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <tr class="spacer"></tr>
                        {% empty %}
                            <tr>
                                <td>Sem cadastros</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if is_paginated %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            {% if page_obj.number > 6 %}
                                <li class="page-item"><a class="page-link" href="?{% url_add_query page=previous_page %}"><i class="fas fa-fast-backward"></i></a></li>
                                <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                            {% endif %}
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">Anteiror</span></li>
                        {% endif %}
                        {% for i in pages %}
                            {% if page_obj.number == i %}
                                <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?{% url_add_query page=i %}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.next_page_number %}">Próximo</a></li>
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=next_page %}"><i class="fas fa-fast-forward"></i></a></li>
                        {% else %}
                            <li class="disabled page-item"><span class="page-link">Próximo</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
'keydown input[type="text"]': function(event, template) {
    if ((27 === event.which) || (13 === event.which)) {
        event.preventDefault();
        //this should delete value from the input
        event.currentTarget.value = "";
    }
}
</script>
{% endblock %} 