core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('', views.index, name='inicio'),
    path('download-report/', views.generate_report, name='download-report'),
    path('download-tag/', views.generate_tags, name='download-tag'),
]

employees/urls.py
from django.urls import path
from .views import EmployeeCreateView, EmployeeDetailView, EmployeeDeleteView, EmployeeListView, EmployeeUpdateView, export_telegrama

app_name = 'employees'
urlpatterns = [
    path('', EmployeeListView.as_view(), name='funcionarios'),
    path('cadastrar/', EmployeeCreateView.as_view(), name='cadastrar'),
    path('<int:pk>', EmployeeDetailView.as_view(), name='funcionario'),
    path('excluir/<int:pk>', EmployeeDeleteView.as_view(), name='excluir'),
    path('editar/<int:pk>', EmployeeUpdateView.as_view(), name='editar'),
    path('download/', export_telegrama, name='download'),
]

maladireta/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('users.urls')),
    path('cargos/', include('positions.urls')),
    path('instituicoes/', include('institutions.urls')),
    path('autoridades/', include('authorities.urls')),
    path('liderancas/', include('leadership.urls')),
    path('partidos/', include('parties.urls')),
    path('candidatos/', include('candidates.urls')),
    path('clientes/', include('customers.urls')),
    path('funcionarios/', include('employees.urls')),
    path('pleitos/', include('solicitations.urls')),
]

employees/models.py
from django.db import models
from django.urls import reverse
import datetime


class EmployeeManager(models.Manager):
    def search(self, query):
        if "Dia:" in query:
            day = query.split(":")[1]
            month = datetime.date.today().month
            return self.get_queryset().filter(models.Q(birth__day=day)).filter(models.Q(birth__month=month))
        elif "Mes:" in query:
            month = query.split(":")[1]
            return self.get_queryset().filter(models.Q(birth__month=month)).order_by('birth__month', 'birth__day')
        elif "Entre: " in query:
            first_day = query.split(":")[1].split(" e ")[0]
            last_day = query.split(":")[1].split(" e ")[1].split(" ")[0]
            month = query.split(" de ")[1]
            return self.get_queryset().filter(models.Q(birth__day__gte=first_day)).filter(models.Q(birth__day__lte=last_day)).filter(models.Q(birth__month=month)).order_by('birth__month', 'birth__day')
        else:    
            return self.get_queryset().filter(models.Q(note__icontains=query) |
                models.Q(name__icontains=query) |
                models.Q(nickname__iexact=query) |
                models.Q(function__icontains=query))

class Employee(models.Model):
    name = models.CharField(max_length=250)
    birth = models.DateField(blank=True, null=True)
    nickname = models.CharField(max_length=80, blank=True, null=True)
    city = models.CharField(max_length=80, blank=True, null=True)
    street = models.CharField(max_length=200, blank=True, null=True)
    number = models.CharField(max_length=10, blank=True, null=True)
    complement = models.CharField(max_length=100, blank=True, null=True)
    cep = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=30, blank=True, null=True)
    neighborhood = models.CharField(max_length=60, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    phone_number = models.CharField(max_length=25, blank=True, null=True)
    cellphone = models.CharField(max_length=25, blank=True, null=True)
    phone_home = models.CharField(max_length=25, blank=True, null=True)
    function = models.CharField(max_length=60, blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    objects = EmployeeManager()

    def get_absolute_url(self):
        return reverse('employees:funcionario', args=[str(self.id)])
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name"]

employees/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"
        labels = {
            'name': 'Nome',
            'birth': 'Nascimento',
            'nickname': 'Pseudonimo',
            'city': 'Cidade',
            'street': 'Rua',
            'number': 'Número',
            'complement': 'Complemento',
            'cep': 'CEP',
            'state': 'Estado',
            'neighborhood': 'Bairro',
            'phone_number': 'Telefone',
            'cellphone': 'Celular',
            'phone_home': 'Residencial',
            'function': 'Função',
            'note': 'Observação'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'birth': forms.DateInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'nickname': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'city': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'street': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'number': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'complement': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'cep': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off', 'data-mask':"00.000-000"}),
            'state': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'neighborhood': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'phone_number': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off', 'data-mask':"(00)0000-0000"}),
            'phone_home': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off', 'data-mask':"(00)0000-0000"}),
            'cellphone': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off', 'data-mask':"(00)00000-0000"}),
            'function': forms.TextInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'email': forms.EmailInput(attrs={'class':"form-control valid", 'autocomplete': 'off'}),
            'note': forms.Textarea(attrs={'class':"form-control valid", 'autocomplete': 'off'})
        }
        error_messages = {
            'name': {
                'required': "Nome é um campo obrigatório"
            }
        }

employees/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse

from .models import Employee
from .forms import EmployeeForm

def export_telegrama(request):
        query = request.session.get("query_filter")
        if query:
            content = [ "{}#Sr(a)#{}#{}#{}#{}#{}#{}#{}#Brasil#######\n".format(employee.name,
                        employee.name, employee.street,
                        employee.neighborhood, employee.number,
                        employee.city, employee.state,
                        employee.cep.replace('.','').replace('-',''))
                        for employee in Employee.objects.search(query)]
        else:
            content = [ "{}#Sr(a)#{}#{}#{}#{}#{}#{}#{}#Brasil#######\n".format(employee.name,
                        employee.name, employee.street,
                        employee.neighborhood, employee.number,
                        employee.city, employee.state,
                        employee.cep.replace('.','').replace('-',''))
                        for employee in Employee.objects.all() ]

        filename = "telegrama_funcionarios.txt"
        response = HttpResponse(content, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
        return response

class EmployeeCreateView(LoginRequiredMixin, CreateView):
    model = Employee
    success_url = reverse_lazy('employees:funcionarios')
    form_class = EmployeeForm

    def form_valid(self, form):
        super(EmployeeCreateView, self).form_valid(form)
        messages.success(self.request, 'Funcionário criado com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

class EmployeeDetailView(LoginRequiredMixin, DetailView):
    model = Employee

class EmployeeDeleteView(LoginRequiredMixin, DeleteView):
    model = Employee
    success_url = reverse_lazy('employees:funcionarios')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Funcionário excluído com sucesso!')
        return super(EmployeeDeleteView, self).delete(request, *args, **kwargs)

class EmployeeListView(LoginRequiredMixin, ListView):
    model = Employee
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not context.get('is_paginated', False):
            return context
        
        paginator = context.get('paginator')
        num_pages = paginator.num_pages
        current_page = context.get('page_obj')
        page_no = current_page.number
        

        if num_pages <= 11 or page_no <= 6:
            pages = [x for x in range(1, min(num_pages + 1, 12))]
        elif page_no > num_pages - 6:
            pages = [x for x in range(num_pages - 10, num_pages + 1)]
        else:
            pages = [x for x in range(page_no - 5, page_no + 6)]
        

        context.update({'pages': pages, 'previous_page': pages[0], 'next_page': pages[-1]})
        return context

    def get_queryset(self):
        filter_value = self.request.GET.get('filter')
        self.request.session['query_origin'] = 'Employee'
        if filter_value:
            context = Employee.objects.search(filter_value)
            self.request.session['query_filter'] = filter_value
        else:
            context = Employee.objects.all()
            self.request.session['query_filter'] = None
        return context

class EmployeeUpdateView(LoginRequiredMixin, UpdateView):
    model = Employee
    success_url = reverse_lazy('employees:funcionarios')
    template_name = "employees/employee_update_form.html"
    form_class = EmployeeForm

    def form_valid(self, form):
        super(EmployeeUpdateView, self).form_valid(form)
        messages.success(self.request, 'Funcionário atualizado com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

templates/employees/employee_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Excluir Funcionário</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
						{% csrf_token %}
                        <div class="form-group">
                            <p>Deseja excluir o funcionário "{{ object }}"?</p>
                        </div>
                        <button type="submit" class="btn btn-danger btn-sm">
                            <i class="fa fa-ban"></i> Excluir
                        </button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/employees/employee_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">Funcionário</div>
				<div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Nome:</label>
                                <input type="text" placeholder="{{ employee.name }}" disabled="" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Pseudonimo:</label>
                                {% if employee.nickname %}
                                    <input type="text" placeholder="{{ employee.nickname }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Nascimento:</label>
                                {% if employee.birth %}
                                    <input type="text" placeholder="{{ employee.birth }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Função:</label>
                                {% if employee.function %}
                                    <input type="text" placeholder="{{ employee.function }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Email:</label>
                                {% if employee.email %}
                                    <input type="text" placeholder="{{ employee.email }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Telefone:</label>
                                {% if employee.phone_number %}
                                    <input type="text" placeholder="{{ employee.phone_number }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Residencial:</label>
                                {% if employee.phone_home %}
                                    <input type="text" placeholder="{{ employee.phone_home }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Celular:</label>
                                {% if employee.cellphone %}
                                    <input type="text" placeholder="{{ employee.cellphone }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Rua:</label>
                                {% if employee.street %}
                                    <input type="text" placeholder="{{ employee.street }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Número:</label>
                                {% if employee.number %}
                                    <input type="text" placeholder="{{ employee.number }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Complemento:</label>
                                {% if employee.complement %}
                                    <input type="text" placeholder="{{ employee.complement }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Bairro:</label>
                                {% if employee.neighborhood %}
                                    <input type="text" placeholder="{{ employee.neighborhood }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Cidade:</label>
                                {% if employee.city %}
                                    <input type="text" placeholder="{{ employee.city }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Estado:</label>
                                {% if employee.state %}
                                    <input type="text" placeholder="{{ employee.state }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">CEP:</label>
                                {% if employee.cep %}
                                    <input type="text" placeholder="{{ employee.cep }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Observação:</label>
                                {% if employee.note %}
                                    <textarea type="text" placeholder="{{ employee.note }}" disabled="" class="form-control"></textarea>
                                {% else %}
                                    <textarea type="text" placeholder="{{ employee.note }}" disabled="" class="form-control"></textarea>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-actions form-group">
                                <button onclick="window.location.href='{% url 'employees:editar' employee.pk %}'" class="btn btn-warning btn-md">Editar</button>
                                <button onclick="window.location.href='{% url 'employees:funcionarios' %}'" class="btn btn-secondary btn-md">Voltar</button>
                            </div>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/employees/employee_list.html
{% extends 'base.html' %}

{% block content %}

{% load app_tags %}

{% if messages %}
{% include 'messages/message.html' %}
{% endif %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- DATA TABLE -->
            <h3 class="title-3 m-b-30">Funcionários</h3>
            <div class="table-data__tool">
                <div class="table-data__tool-left">
                    <form method="get">
                        <div class="rs-select2--light rs-select2--lg">
                            <input type="text" title="Dia: xx&#013;Mes: xx&#013;Entre: 01 e 15 de 06" id="filter" name="filter" class="form-control">
                        </div>
                        <button class="au-btn-filter">
                            <i class="zmdi zmdi-search"></i>Buscar</button>
                    </form>
                </div>
                <div class="table-data__tool-right">
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'employees:cadastrar' %}'">
                        <i class="zmdi zmdi-plus"></i>Criar</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'employees:download' %}'">
                        <i class="zmdi zmdi-email"></i>Correios</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'core:download-report' %}'">
                        <i class="zmdi zmdi-archive"></i>Relatório</button>
                </div>
                
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Pseudonimo</th>
                            <th>Função</th>
                            <th>Celular</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in object_list %}
                            <tr>
                                <td>{{ employee.name }}</td>
                                <td>{{ employee.nickname }}</td>
                                <td>{{ employee.function }}</td>
                                <td>{{ employee.cellphone }}</td>
                                <td>
                                    <div class="table-data-feature">
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Detalhes" onclick="window.location.href='{% url 'employees:funcionario' employee.pk %}'">
                                            <i class="zmdi zmdi-file-text"></i>
                                        </button>
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Editar" onclick="window.location.href='{% url 'employees:editar' employee.pk %}'">
                                            <i class="zmdi zmdi-edit"></i>
                                        </button>
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Excluir" onclick="window.location.href='{% url 'employees:excluir' employee.pk %}'">
                                            <i class="zmdi zmdi-delete"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                            <tr class="spacer"></tr>
                        {% empty %}
                            <tr>
                                <td>Sem cadastros</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- END DATA TABLE -->
            {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    {% if page_obj.number > 6 %}
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=previous_page %}"><i class="fas fa-fast-backward"></i></a></li>
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                    {% endif %}
                {% else %}
                    <li class="page-item disabled"><span class="page-link">Anteiror</span></li>
                {% endif %}
                {% for i in pages %}
                    {% if page_obj.number == i %}
                        <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=i %}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.next_page_number %}">Próximo</a></li>
                    <li class="page-item"><a class="page-link" href="?{% url_add_query page=next_page %}"><i class="fas fa-fast-forward"></i></a></li>
                {% else %}
                    <li class="disabled page-item"><span class="page-link">Próximo</span></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script>
'keydown input[type="text"]': function(event, template) {
    if ((27 === event.which) || (13 === event.which)) {
        event.preventDefault();
        //this should delete value from the input
        event.currentTarget.value = "";
    }
}
</script>
{% endblock %} 