candidates/urls.py
from django.urls import path
from .views import CandidateCreateView, CandidateDetailView, CandidateDeleteView, CandidateListView, CandidateUpdateView

app_name = 'candidates'
urlpatterns = [
    path('', CandidateListView.as_view(), name='candidatos'),
    path('cadastrar/', CandidateCreateView.as_view(), name='cadastrar'),
    path('<int:pk>', CandidateDetailView.as_view(), name='candidato'),
    path('excluir/<int:pk>', CandidateDeleteView.as_view(), name='excluir'),
    path('editar/<int:pk>', CandidateUpdateView.as_view(), name='editar'),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('', views.index, name='inicio'),
    path('download-report/', views.generate_report, name='download-report'),
    path('download-tag/', views.generate_tags, name='download-tag'),
]

maladireta/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('users.urls')),
    path('cargos/', include('positions.urls')),
    path('instituicoes/', include('institutions.urls')),
    path('autoridades/', include('authorities.urls')),
    path('liderancas/', include('leadership.urls')),
    path('partidos/', include('parties.urls')),
    path('candidatos/', include('candidates.urls')),
    path('clientes/', include('customers.urls')),
    path('funcionarios/', include('employees.urls')),
    path('pleitos/', include('solicitations.urls')),
]

candidates/models.py
from django.db import models
from django.urls import reverse

class CandidateManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(models.Q(party__name__icontains=query) |
            models.Q(position__position__icontains=query) |
            models.Q(name__icontains=query) |
            models.Q(number__iexact=query) |
            models.Q(union__icontains=query))

class Candidate(models.Model):
    name = models.CharField(max_length=250)
    number = models.IntegerField()
    union = models.CharField(max_length=350, blank=True, null=True)
    party = models.ForeignKey('parties.Party', on_delete=models.SET_NULL, null=True)
    position = models.ForeignKey('positions.Position', on_delete=models.SET_NULL, null=True)
    votes = models.IntegerField(blank=True, null=True)

    objects = CandidateManager()

    def get_absolute_url(self):
        return reverse('candidate:Candidate', args=[str(self.id)])
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name"]

candidates/forms.py
from django import forms
from .models import Candidate

class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = '__all__'
        labels = {
            'name': 'Nome',
            'number': 'Número',
            'union': 'Coligação',
            'votes': 'Votos',
            'party': 'Partido',
            'position': 'Cargo'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'number': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'union': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'votes': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'party': forms.Select(attrs={'class':"form-control cc-name valid"}),
            'position': forms.Select(attrs={'class':"form-control cc-name valid"})
        }
        error_messages = {
            'name': {
                'required': "Nome é um campo obrigatório"
            },
            'number': {
                'required': "Número é um campo obrigatório"
            },
            'party': {
                'required': "Partido é um campo obrigatório"
            },
            'position': {
                'required': "Cargo é um campo obrigatório"
            },
        }

candidates/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.http import HttpResponseRedirect

from .models import Candidate
from .forms import CandidateForm

class CandidateCreateView(LoginRequiredMixin, CreateView):
    model = Candidate
    success_url = reverse_lazy('candidates:candidatos')
    form_class = CandidateForm

    def form_valid(self, form):
        super(CandidateCreateView, self).form_valid(form)
        messages.success(self.request, 'Candidato criado com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

class CandidateDetailView(LoginRequiredMixin, DetailView):
    model = Candidate

class CandidateDeleteView(LoginRequiredMixin, DeleteView):
    model = Candidate
    success_url = reverse_lazy('candidates:candidatos')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Candidato excluído com sucesso!')
        return super(CandidateDeleteView, self).delete(request, *args, **kwargs)

class CandidateListView(LoginRequiredMixin, ListView):
    model = Candidate
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not context.get('is_paginated', False):
            return context
        
        paginator = context.get('paginator')
        num_pages = paginator.num_pages
        current_page = context.get('page_obj')
        page_no = current_page.number
        

        if num_pages <= 11 or page_no <= 6:
            pages = [x for x in range(1, min(num_pages + 1, 12))]
        elif page_no > num_pages - 6:
            pages = [x for x in range(num_pages - 10, num_pages + 1)]
        else:
            pages = [x for x in range(page_no - 5, page_no + 6)]
        

        context.update({'pages': pages, 'previous_page': pages[0], 'next_page': pages[-1]})
        return context

    def get_queryset(self):
        filter_value = self.request.GET.get('filter')
        self.request.session['query_origin'] = 'Candidate'
        if filter_value:
            context = Candidate.objects.search(filter_value)
            self.request.session['query_filter'] = filter_value
        else:
            context = Candidate.objects.all()
            self.request.session['query_filter'] = None
        return context

class CandidateUpdateView(LoginRequiredMixin, UpdateView):
    model = Candidate
    success_url = reverse_lazy('candidates:candidatos')
    template_name = 'candidates/candidate_update_form.html'
    form_class = CandidateForm

    def form_valid(self, form):
        super(CandidateUpdateView, self).form_valid(form)
        messages.success(self.request, 'Candidato atualizado com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

templates/candidates/candidate_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-6">
			<div class="card">
				<div class="card-header">Excluir Candidato</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
						{% csrf_token %}
                        <div class="form-group">
                            <p>Deseja excluir o candidato "{{ object }}"?</p>
                        </div>
                        <button type="submit" class="btn btn-danger btn-md">
                            <i class="fa fa-ban"></i> Excluir
                        </button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/candidates/candidate_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
                <div class="card-header">Candidato</div>
				<div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Nome:</label>
                                <input type="text" placeholder="{{ candidate.name }}" disabled="" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Cargo:</label>
                                {% if candidate.position %}
                                    <input type="text" placeholder="{{ candidate.position }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Partido:</label>
                                {% if candidate.party %}
                                    <input type="text" placeholder="{{ candidate.party }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Número:</label>
                                {% if candidate.number %}
                                    <input type="text" placeholder="{{ candidate.number }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Votos:</label>
                                {% if candidate.votes %}
                                    <input type="text" placeholder="{{ candidate.votes }}" disabled="" class="form-control">
                                {% else %}
                                    <input type="text" placeholder="" disabled="" class="form-control">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-actions form-group">
                                <button onclick="window.location.href='{% url 'candidates:editar' candidate.pk %}'" class="btn btn-warning btn-md">Editar</button>
                                <button onclick="window.location.href='{% url 'candidates:candidatos' %}'" class="btn btn-secondary btn-md">Voltar</button>
                            </div>
                        </div>
                    </div>
                </div
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/candidates/candidate_form.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
{% include 'messages/error.html' %}
{% endif %}

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">Criar Candidato</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
						{% csrf_token %}
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.name.label_tag }}</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.position.label_tag }}</label>
                                    {{ form.position }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.party.label_tag }}</label>
                                    {{ form.party }}
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.number.label_tag }}</label>
                                    {{ form.number }}
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.votes.label_tag }}</label>
                                    {{ form.votes }}
                                </div>
                            </div>
                        </div>
                        <div class="form-actions form-group">
                            <button type="submit" class="btn btn-primary btn-md">Salvar</button>
                        </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/candidates/candidate_list.html
{% extends 'base.html' %}

{% block content %}

{% load app_tags %}

{% if messages %}
{% include 'messages/message.html' %}
{% endif %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- DATA TABLE -->
            <h3 class="title-3 m-b-30">Candidatos</h3>
            <div class="table-data__tool">
                <div class="table-data__tool-left">
                    <form method="get">
                        <div class="rs-select2--light rs-select2--lg">
                            <input type="text" id="filter" name="filter" class="form-control">
                        </div>
                        <button class="au-btn-filter">
                            <i class="zmdi zmdi-search"></i>Buscar</button>
                    </form>
                </div>
                <div class="table-data__tool-right">
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'candidates:cadastrar' %}'">
                        <i class="zmdi zmdi-plus"></i>Criar</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'core:download-report' %}'">
                        <i class="zmdi zmdi-archive"></i>Relatório</button>
                </div>
                
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Partido</th>
                            <th>Número</th>
                            <th>Cargo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for candidate in object_list %}
                            <tr>
                                <td>{{ candidate.name }}</td>
                                <td>{{ candidate.party }}</td>
                                <td>{{ candidate.number }}</td>
                                <td>{{ candidate.position }}</td>
                                <td>
                                    <div class="table-data-feature">
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Detalhes" onclick="window.location.href='{% url 'candidates:candidato' candidate.pk %}'">
                                            <i class="zmdi zmdi-file-text"></i>
                                        </button>
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Editar" onclick="window.location.href='{% url 'candidates:editar' candidate.pk %}'">
                                            <i class="zmdi zmdi-edit"></i>
                                        </button>
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Excluir" onclick="window.location.href='{% url 'candidates:excluir' candidate.pk %}'">
                                            <i class="zmdi zmdi-delete"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                            <tr class="spacer"></tr>
                        {% empty %}
                            <tr>
                                <td>Sem cadastros</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- END DATA TABLE -->
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        {% if page_obj.number > 6 %}
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=previous_page %}"><i class="fas fa-fast-backward"></i></a></li>
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                        {% endif %}
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">Anteiror</span></li>
                    {% endif %}
                    {% for i in pages %}
                        {% if page_obj.number == i %}
                            <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=i %}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.next_page_number %}">Próximo</a></li>
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=next_page %}"><i class="fas fa-fast-forward"></i></a></li>
                    {% else %}
                        <li class="disabled page-item"><span class="page-link">Próximo</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

<script>
'keydown input[type="text"]': function(event, template) {
    if ((27 === event.which) || (13 === event.which)) {
        event.preventDefault();
        //this should delete value from the input
        event.currentTarget.value = "";
    }
}
</script>
{% endblock %} 

templates/candidates/candidate_update_form.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
{% include 'messages/error.html' %}
{% endif %}

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">Editar Candidato</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
						{% csrf_token %}
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.name.label_tag }}</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.position.label_tag }}</label>
                                    {{ form.position }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.party.label_tag }}</label>
                                    {{ form.party }}
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.number.label_tag }}</label>
                                    {{ form.number }}
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="cc-payment" class="control-label mb-1">{{ form.votes.label_tag }}</label>
                                    {{ form.votes }}
                                </div>
                            </div>
                        </div>
                        <div class="form-actions form-group">
                            <button type="submit" class="btn btn-primary btn-md">Salvar</button>
                        </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}