core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('', views.index, name='inicio'),
    path('download-report/', views.generate_report, name='download-report'),
    path('download-tag/', views.generate_tags, name='download-tag'),
]

leadership/urls.py
from django.urls import path
from .views import LeadershipCreateView, LeadershipDetailView, LeadershipDeleteView, LeadershipListView, LeadershipUpdateView, export_telegrama

app_name = 'leadership'
urlpatterns = [
    path('', LeadershipListView.as_view(), name='liderancas'),
    path('cadastrar/', LeadershipCreateView.as_view(), name='cadastrar'),
    path('<int:pk>', LeadershipDetailView.as_view(), name='lideranca'),
    path('excluir/<int:pk>', LeadershipDeleteView.as_view(), name='excluir'),
    path('editar/<int:pk>', LeadershipUpdateView.as_view(), name='editar'),
    path('download/', export_telegrama, name='download'),
]

maladireta/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('users.urls')),
    path('cargos/', include('positions.urls')),
    path('instituicoes/', include('institutions.urls')),
    path('autoridades/', include('authorities.urls')),
    path('liderancas/', include('leadership.urls')),
    path('partidos/', include('parties.urls')),
    path('candidatos/', include('candidates.urls')),
    path('clientes/', include('customers.urls')),
    path('funcionarios/', include('employees.urls')),
    path('pleitos/', include('solicitations.urls')),
]

leadership/models.py
from django.db import models
from django.urls import reverse
import datetime

class LeadershipManager(models.Manager):
    def search(self, query):
        if "Dia:" in query:
            day = query.split(":")[1]
            month = datetime.date.today().month
            return self.get_queryset().filter(models.Q(birth__day=day)).filter(models.Q(birth__month=month))
        elif "Mes:" in query:
            month = query.split(":")[1]
            return self.get_queryset().filter(models.Q(birth__month=month)).order_by('birth__month', 'birth__day')
        elif "Cargo: " in query:
            position = query.split("Cargo: ")[1]
            return self.get_queryset().filter(models.Q(position__position__iexact=position))
        elif "Referencia: " in query:
            office = query.split("Referencia: ")[1]
            return self.get_queryset().filter(models.Q(office__icontains=office))
        elif "Entre: " in query:
            first_day = query.split(":")[1].split(" e ")[0]
            last_day = query.split(":")[1].split(" e ")[1].split(" ")[0]
            month = query.split(" de ")[1]
            return self.get_queryset().filter(models.Q(birth__day__gte=first_day)).filter(models.Q(birth__day__lte=last_day)).filter(models.Q(birth__month=month)).order_by('birth__month', 'birth__day')
        else:
            return self.get_queryset().filter(models.Q(name__icontains=query) | 
                models.Q(nickname__icontains=query) | 
                models.Q(note__icontains=query) | 
                models.Q(rg__iexact=query) | 
                models.Q(cpf__iexact=query))

class Leadership(models.Model):
    name = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=25, blank=True, null=True)
    cellphone = models.CharField(max_length=25, blank=True, null=True)
    phone_home = models.CharField(max_length=25, blank=True, null=True)
    city = models.CharField(max_length=80, blank=True, null=True)
    street = models.CharField(max_length=200, blank=True, null=True)
    number = models.CharField(max_length=10, blank=True, null=True)
    complement = models.CharField(max_length=150, blank=True, null=True)
    cep = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    neighborhood = models.CharField(max_length=60, blank=True, null=True)
    rg = models.CharField(max_length=20, blank=True, null=True)
    cpf = models.CharField(max_length=20, blank=True, null=True)
    birth = models.DateField(blank=True, null=True)
    updated = models.DateField(auto_now_add=True)
    nickname = models.CharField(max_length=60, blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    position = models.ForeignKey('positions.Position', on_delete=models.SET_NULL, blank=True, null=True)
    office = models.CharField(max_length=150, blank=True, null=True)
    pendency = models.CharField(max_length=350, blank=True, null=True)

    objects = LeadershipManager()

    def get_absolute_url(self):
        return reverse('leadership:lideranca', args=[str(self.id)])
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name"]

leadership/forms.py
from django import forms
from .models import Leadership

class LeadershipForm(forms.ModelForm):
    class Meta:
        model = Leadership
        fields = '__all__'
        labels = {
            'name': 'Nome',
            'phone_number': 'Telefone',
            'phone_home': 'Residencial',
            'cellphone': 'Celular',
            'city': 'Cidade',
            'street': 'Rua',
            'number': 'Número',
            'complement': 'Complemento',
            'cep': 'CEP',
            'state': 'Estado',
            'neighborhood': 'Bairro',
            'rg': 'RG',
            'cpf': 'CPF',
            'birth': 'Nascimento',
            'nickname': 'Pseudonimo',
            'note': 'Observação',
            'position': 'Cargo',
            'office': 'Referência',
            'pendency': 'Pendência'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'phone_number': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"(00)0000-0000"}),
            'phone_home': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"(00)0000-0000"}),
            'cellphone': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"(00)00000-0000"}),
            'city': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'street': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'number': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'complement': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'cep': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"00.000-000"}),
            'state': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'neighborhood': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'rg': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'cpf': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off', 'data-mask':"000.000.000-00"}),
            'birth': forms.DateInput(attrs={'class':"form-control cc-name valid", 'type':'text', 'autocomplete': 'off', 'data-mask':"00/00/0000"}),
            'nickname': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'note': forms.Textarea(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'email': forms.EmailInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'position': forms.Select(attrs={'class':"form-control cc-name valid"}),
            'office': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'}),
            'pendency': forms.TextInput(attrs={'class':"form-control cc-name valid", 'autocomplete': 'off'})
        }
        error_messages = {
            'name': {
                'required': "Nome é um campo obrigatório"
            }
        }

leadership/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse

from .models import Leadership
from  positions.models import Position
from .forms import LeadershipForm

def export_telegrama(request):
        query = request.session.get("query_filter")
        if query:
            content = []
            for leadership in Leadership.objects.search(query):
                abbreviation = "Sr(a)"
                if leadership.position:
                    abbreviation = Position.objects.search(leadership.position)[0].abbreviation
                content.append("{}#{}#{}#{}#{}#{}#{}#{}#{}#Brasil#######\n".format(leadership.name, abbreviation.replace("\n",''),
                        leadership.name, leadership.street,
                        leadership.neighborhood, leadership.number,
                        leadership.city, leadership.state,
                        leadership.cep.replace('.','').replace('-','')))
        else:
            content = []
            for leadership in Leadership.objects.all():
                abbreviation = "Sr(a)"
                if leadership.position:
                    abbreviation = Position.objects.search(leadership.position)[0].abbreviation
                content.append("{}#{}#{}#{}#{}#{}#{}#{}#{}#Brasil#######\n".format(leadership.name, abbreviation.replace("\n",''),
                        leadership.name, leadership.street,
                        leadership.neighborhood, leadership.number,
                        leadership.city, leadership.state,
                        leadership.cep.replace('.','').replace('-','')))

        filename = "telegrama_lideranças.txt"
        response = HttpResponse(content, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
        return response

class LeadershipCreateView(LoginRequiredMixin, CreateView):
    model = Leadership
    form_class = LeadershipForm
    success_url = reverse_lazy('leadership:liderancas')

    def form_valid(self,form):
        super(LeadershipCreateView,self).form_valid(form)
        messages.success(self.request, 'Liderança criada com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

class LeadershipDetailView(LoginRequiredMixin, DetailView):
    model = Leadership

class LeadershipDeleteView(LoginRequiredMixin, DeleteView):
    model = Leadership
    success_url = reverse_lazy('leadership:liderancas')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Liderança excluída com sucesso!')
        return super(LeadershipDeleteView, self).delete(request, *args, **kwargs)

class LeadershipListView(LoginRequiredMixin, ListView):
    model = Leadership
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not context.get('is_paginated', False):
            return context
        
        paginator = context.get('paginator')
        num_pages = paginator.num_pages
        current_page = context.get('page_obj')
        page_no = current_page.number
        

        if num_pages <= 11 or page_no <= 6:
            pages = [x for x in range(1, min(num_pages + 1, 12))]
        elif page_no > num_pages - 6:
            pages = [x for x in range(num_pages - 10, num_pages + 1)]
        else:
            pages = [x for x in range(page_no - 5, page_no + 6)]
        

        context.update({'pages': pages, 'previous_page': pages[0], 'next_page': pages[-1]})
        return context

    def get_queryset(self):
        filter_value = self.request.GET.get('filter')
        self.request.session['query_origin'] = 'Leadership'
        if filter_value:
            context = Leadership.objects.search(filter_value)
            self.request.session['query_filter'] = filter_value
        else:
            context = Leadership.objects.all()
            self.request.session['query_filter'] = None
        return context

class LeadershipUpdateView(LoginRequiredMixin, UpdateView):
    model = Leadership
    form_class = LeadershipForm
    template_name = 'leadership/leadership_update_form.html'
    success_url = reverse_lazy('leadership:liderancas')

    def form_valid(self,form):
        super(LeadershipUpdateView,self).form_valid(form)
        messages.success(self.request, 'Liderança atualizada com sucesso!')
        return HttpResponseRedirect(self.get_success_url())
        

templates/leadership/leadership_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-6">
			<div class="card">
				<div class="card-header">Excluir Liderança</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
						{% csrf_token %}
                        <div class="form-group">
                            <p>Deseja excluir a liderança "{{ object }}"?</p>
                        </div>
                        <button type="submit" class="btn btn-danger btn-md">
                            <i class="fa fa-ban"></i> Excluir
                        </button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/leadership/leadership_form.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
{% include 'messages/error.html' %}
{% endif %}

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">Criar Liderança</div>
				<div class="card-body">
					<form action="" method="post" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.name.label_tag }}</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.nickname.label_tag }}</label>
                                    {{ form.nickname }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.birth.label_tag }}</label>
                                    {{ form.birth }}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.cpf.label_tag }}</label>
                                    {{ form.cpf }}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.rg.label_tag }}</label>
                                    {{ form.rg }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.phone_number.label_tag }}</label>
                                    {{ form.phone_number }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.cellphone.label_tag }}</label>
                                    {{ form.cellphone }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.phone_home.label_tag }}</label>
                                    {{ form.phone_home }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.email.label_tag }}</label>
                                    {{ form.email }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.street.label_tag }}</label>
                                    {{ form.street }}
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.number.label_tag }}</label>
                                    {{ form.number }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.complement.label_tag }}</label>
                                    {{ form.complement }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.neighborhood.label_tag }}</label>
                                    {{ form.neighborhood }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.city.label_tag }}</label>
                                    {{ form.city }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.state.label_tag }}</label>
                                    {{ form.state }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.cep.label_tag }}</label>
                                    {{ form.cep }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.position.label_tag }}</label>
                                    {{ form.position }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.office.label_tag }}</label>
                                    {{ form.office }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.pendency.label_tag }}</label>
                                    {{ form.pendency }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="control-label mb-1">{{ form.note.label_tag }}</label>
                                    {{ form.note }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-actions form-group">
                                    <button type="submit" class="btn btn-primary btn-md">Salvar</button>
                                </div>
                            </div>
                        </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/leadership/leadership_list.html
{% extends 'base.html' %}

{% block content %}

{% load app_tags %}

{% if messages %}
{% include 'messages/message.html' %}
{% endif %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- DATA TABLE -->
            <h3 class="title-3 m-b-30">Lideranças</h3>
            <div class="table-data__tool">
                <div class="table-data__tool-left">
                    <form method="get">
                        <div class="rs-select2--light rs-select2--lg">
                            <input type="text" title="Referencia: busca&#013;Cargo: busca&#013;Dia: xx&#013;Mes: xx&#013;Entre: 01 e 15 de 06" id="filter" name="filter" class="form-control">
                        </div>
                        <button class="au-btn-filter">
                            <i class="zmdi zmdi-search"></i>Buscar</button>
                    </form>
                </div>
                <div class="table-data__tool-right">
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'leadership:cadastrar' %}'">
                        <i class="zmdi zmdi-plus"></i>Criar</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'leadership:download' %}'">
                        <i class="zmdi zmdi-email"></i>Correios</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'core:download-report' %}'">
                        <i class="zmdi zmdi-archive"></i>Relatório</button>
                    <button class="au-btn au-btn-icon au-btn-load au-btn--small" onclick="window.location.href='{% url 'core:download-tag' %}'">
                        <i class="zmdi zmdi-archive"></i>Etiquetas</button>
                </div>
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Pseudonimo</th>
                            <th>Email</th>
                            <th>Cargo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for leadership in object_list %}
                            <tr>
                                <td>{{ leadership.name }}</td>
                                <td>{{ leadership.nickname }}</td>
                                <td>{{ leadership.email }}</td>
                                <td>{{ leadership.position }}</td>
                                <td>
                                    <div class="table-data-feature">
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Detalhes" onclick="window.location.href='{% url 'leadership:lideranca' leadership.pk %}'">
                                            <i class="zmdi zmdi-file-text"></i>
                                        </button>
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Editar" onclick="window.location.href='{% url 'leadership:editar' leadership.pk %}'">
                                            <i class="zmdi zmdi-edit"></i>
                                        </button>
                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Excluir" onclick="window.location.href='{% url 'leadership:excluir' leadership.pk %}'">
                                            <i class="zmdi zmdi-delete"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                            <tr class="spacer"></tr>
                        {% empty %}
                            <tr>
                                <td>Sem cadastros</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- END DATA TABLE -->
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        {% if page_obj.number > 6 %}
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=previous_page %}"><i class="fas fa-fast-backward"></i></a></li>
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.previous_page_number %}">Anterior</a></li>
                        {% endif %}
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">Anteiror</span></li>
                    {% endif %}
                    {% for i in pages %}
                        {% if page_obj.number == i %}
                            <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?{% url_add_query page=i %}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=page_obj.next_page_number %}">Próximo</a></li>
                        <li class="page-item"><a class="page-link" href="?{% url_add_query page=next_page %}"><i class="fas fa-fast-forward"></i></a></li>
                    {% else %}
                        <li class="disabled page-item"><span class="page-link">Próximo</span></li>
                    {% endif %}
                </ul>
                {% endif %}
        </div>
    </div>
</div>

<script>
'keydown input[type="text"]': function(event, template) {
    if ((27 === event.which) || (13 === event.which)) {
        event.preventDefault();
        //this should delete value from the input
        event.currentTarget.value = "";
    }
}
</script>
{% endblock %} 